# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
# Spring Configuration
spring:
  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/TaskFlow?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        format_sql: false
    database: mysql
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    driver-class-name: com.mysql.cj.jdbc.Driver
    liquibase-schema: TaskFlow

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
